# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelaInicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaPrinciapal(object):
    def setupUi(self, TelaPrinciapal):
        TelaPrinciapal.setObjectName("TelaPrinciapal")
        TelaPrinciapal.resize(440, 382)
        TelaPrinciapal.setStyleSheet("font: 75 8pt \"Arial Narrow\";\n"
"background-color:rgb(85, 170, 127)")
        TelaPrinciapal.setIconSize(QtCore.QSize(60, 60))
        self.centralwidget = QtWidgets.QWidget(TelaPrinciapal)
        self.centralwidget.setObjectName("centralwidget")
        self.lblTituloPaginaInicial = QtWidgets.QLabel(self.centralwidget)
        self.lblTituloPaginaInicial.setGeometry(QtCore.QRect(90, 10, 241, 41))
        self.lblTituloPaginaInicial.setStyleSheet("font: 75 36pt \"Rockwell\";\n"
"")
        self.lblTituloPaginaInicial.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lblTituloPaginaInicial.setObjectName("lblTituloPaginaInicial")
        self.btnpesquisar = QtWidgets.QPushButton(self.centralwidget)
        self.btnpesquisar.setGeometry(QtCore.QRect(10, 120, 75, 23))
        self.btnpesquisar.setStyleSheet("background-color: rgb(255, 255, 0);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/arquivo-de-documento.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnpesquisar.setIcon(icon)
        self.btnpesquisar.setIconSize(QtCore.QSize(16, 16))
        self.btnpesquisar.setObjectName("btnpesquisar")
        self.btncomprar = QtWidgets.QPushButton(self.centralwidget)
        self.btncomprar.setGeometry(QtCore.QRect(100, 120, 75, 23))
        self.btncomprar.setStyleSheet("background-color: rgb(255, 255, 0);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/carrinho-de-compras.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btncomprar.setIcon(icon1)
        self.btncomprar.setObjectName("btncomprar")
        TelaPrinciapal.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(TelaPrinciapal)
        self.statusBar.setObjectName("statusBar")
        TelaPrinciapal.setStatusBar(self.statusBar)

        self.retranslateUi(TelaPrinciapal)
        QtCore.QMetaObject.connectSlotsByName(TelaPrinciapal)

    def retranslateUi(self, TelaPrinciapal):
        _translate = QtCore.QCoreApplication.translate
        TelaPrinciapal.setWindowTitle(_translate("TelaPrinciapal", "Biblioteca - Pagina Principal"))
        self.lblTituloPaginaInicial.setText(_translate("TelaPrinciapal", "Bem Vindo"))
        self.btnpesquisar.setText(_translate("TelaPrinciapal", "Pesquisar"))
        self.btncomprar.setText(_translate("TelaPrinciapal", "Comprar"))
